@echo off


echo Wilkommen bei Area31 !

pause


echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...
echo Loading ! Please Wait ...
echo Loading ! Please Wait...

pause 

echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...
echo Loading Scripts ! Please Wait...

pause 


echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...
echo Verbinde mit DarkServer-14.34.23.89.01 ...

pause 

echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...
echo Verbinde mit RUSIA-12.45.69.23.58 ...

pause 


echo Alle Server sind nun einsatzbereit du kanst los legen!

pause




pause
echo Gebe die gewünschte IP von dem Server der plattgemacht werden soll!
pause
pause
pause
pause
pause
echo Es gab einen Fehler mit der IP!
pause


pause
echo Ermitle Fehler ...
echo Ermitle Fehler ...
echo Ermitle Fehler ...
echo Ermitle Fehler ...
echo Ermitle Fehler ...
echo Ermitle Fehler ...
echo Ermitle Fehler ...
echo Ermitle Fehler ...
echo Ermitle Fehler ...
echo Ermitle Fehler ...
pause
echo Reloade RUSIA-12.45.69.23.58 ...
pause
echo Reloade DarkServer-14.34.23.89.0
pause 
echo Fehler gefunden !
pause 
echo Hinweis: Area31 ist ein Prank Projekt von TxtCloudDE . Schönen Tag ncoh und fall nicht aus so was mehr rein ;D
